# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
from PyQt5.QtWidgets import QLabel, QShortcut
from PyQt5.QtGui import QKeySequence
from PyQt5.QtCore import Qt
from widget_camera_item import Widget_Camera_Item


class Ui_MainWindow(QMainWindow):

    def __init__(self):
        super().__init__()
        self.setupUi()
        QShortcut(QKeySequence(Qt.Key_C), self, activated=self.Key_C)
        self.grid_layout_cameras = QtWidgets.QGridLayout()
        self.grid_layout_cameras.setContentsMargins(0, 0, 0, 0)
        self.cam_i = Widget_Camera_Item()

        for i in range(3):  # rows
            for j in range(3):  # cols
                self.grid_layout_cameras.addWidget(QtWidgets.QWidget(), i, j)

        self.frame_cameras.setLayout(self.grid_layout_cameras)

    def Key_C(self):
        self.menu.setVisible(not self.menu.isVisible())

    def setupUi(self):
        expand = 10
        self.setObjectName("MainWindow")
        self.resize(574, 395)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.layout_main = QtWidgets.QGridLayout(self.centralwidget)
        self.layout_main.setObjectName("layout_main")
        self.frame_cameras = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_cameras.sizePolicy().hasHeightForWidth())
        self.frame_cameras.setSizePolicy(sizePolicy)
        self.frame_cameras.setStyleSheet("background: gray;")
        self.frame_cameras.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_cameras.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_cameras.setObjectName("frame_cameras")
        self.layout_main.addWidget(self.frame_cameras, 0, 1, 1, 1)
        self.menu = QtWidgets.QFrame(self.centralwidget)
        self.menu.setMinimumSize(QtCore.QSize(128, 0))
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.layout_menu = QtWidgets.QGridLayout(self.menu)
        self.layout_menu.setObjectName("layout_menu")
        self.btn_search = QtWidgets.QPushButton(self.menu)
        self.btn_search.setObjectName("btn_search")
        self.layout_menu.addWidget(self.btn_search, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.menu)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layout_menu.addWidget(self.line, 3, 0, 1, 1)
        self.btn_config = QtWidgets.QPushButton(self.menu)
        self.btn_config.setObjectName("btn_config")
        self.layout_menu.addWidget(self.btn_config, 1, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.menu)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.layout_menu.addWidget(self.line_2, 5, 0, 1, 1)
        self.btn_view_2d_map = QtWidgets.QPushButton(self.menu)
        self.btn_view_2d_map.setObjectName("btn_view_2d_map")
        self.layout_menu.addWidget(self.btn_view_2d_map, 0, 0, 1, 1)
        self.layout_main.addWidget(self.menu, 0, 0, 1, 1)
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_search.setText(_translate("MainWindow", "Search"))
        self.btn_config.setText(_translate("MainWindow", "View Information"))
        self.btn_view_2d_map.setText(_translate("MainWindow", "View 2D map"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_MainWindow()
    ui.show()
    sys.exit(app.exec_())
