# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
# from queue import Queue

import cv2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtGui import QPixmap, QPainter
import numpy as np


class Widget_Camera_Item(QtWidgets.QWidget):
    sig_new_cam_inf = pyqtSignal(int, str, int, bool)
    sig_cancel_add_cam = pyqtSignal()

    def __init__(self):
        super().__init__()
        self.installEventFilter(self)

        self.current_frames = []

    # def paintEvent(self, event):
    #     pass

    def setupUi(self):
        self.setObjectName("form_camera")
        self.resize(245, 108)
        self.setStyleSheet("")
        self.layout_main = QtWidgets.QGridLayout(self)
        self.layout_main.setContentsMargins(0, 0, 0, 0)
        self.layout_main.setSpacing(0)
        self.layout_main.setObjectName("layout_main")
        self.group_settings = QtWidgets.QGroupBox(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_settings.sizePolicy().hasHeightForWidth())
        self.group_settings.setSizePolicy(sizePolicy)
        self.group_settings.setMinimumSize(QtCore.QSize(0, 0))
        self.group_settings.setTitle("")
        self.group_settings.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.group_settings.setFlat(False)
        self.group_settings.setObjectName("group_settings")
        self.layout_settings = QtWidgets.QGridLayout(self.group_settings)
        self.layout_settings.setObjectName("layout_settings")
        self.btn_cancel = QtWidgets.QPushButton(self.group_settings)
        self.btn_cancel.setObjectName("btn_cancel")
        self.layout_settings.addWidget(self.btn_cancel, 2, 3, 1, 2)
        self.btn_apply = QtWidgets.QPushButton(self.group_settings)
        self.btn_apply.setObjectName("btn_apply")
        self.layout_settings.addWidget(self.btn_apply, 2, 0, 1, 2)
        self.label_show = QtWidgets.QLabel(self.group_settings)
        self.label_show.setObjectName("label_show")
        self.layout_settings.addWidget(self.label_show, 1, 3, 1, 1)
        self.txt_rtsp = QtWidgets.QLineEdit(self.group_settings)
        self.txt_rtsp.setObjectName("txt_rtsp")
        self.layout_settings.addWidget(self.txt_rtsp, 0, 4, 1, 1)
        self.cb_display = QtWidgets.QCheckBox(self.group_settings)
        self.cb_display.setText("")
        self.cb_display.setObjectName("cb_display")
        self.layout_settings.addWidget(self.cb_display, 1, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(12, 12, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.layout_settings.addItem(spacerItem, 0, 2, 1, 1)
        self.label_rtsp = QtWidgets.QLabel(self.group_settings)
        self.label_rtsp.setObjectName("label_rtsp")
        self.layout_settings.addWidget(self.label_rtsp, 0, 3, 1, 1)
        self.txt_camera_id = QtWidgets.QLineEdit(self.group_settings)
        self.txt_camera_id.setObjectName("txt_camera_id")
        self.layout_settings.addWidget(self.txt_camera_id, 0, 1, 1, 1)
        self.label_camera_id = QtWidgets.QLabel(self.group_settings)
        self.label_camera_id.setObjectName("label_camera_id")
        self.layout_settings.addWidget(self.label_camera_id, 0, 0, 1, 1)
        self.combo_features = QtWidgets.QComboBox(self.group_settings)
        self.combo_features.setObjectName("combo_features")
        for i in range(len(self.cb_model_dict)):
            self.combo_features.addItem("")
        self.layout_settings.addWidget(self.combo_features, 1, 0, 1, 2)
        self.btn_delete_cam = QtWidgets.QPushButton(self.group_settings)
        self.btn_delete_cam.setObjectName("btn_delete_cam")
        self.layout_settings.addWidget(self.btn_delete_cam, 3, 0, 1, 5)
        self.layout_main.addWidget(self.group_settings, 0, 0, 1, 2)
        self.camera_frame = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_frame.sizePolicy().hasHeightForWidth())
        self.camera_frame.setSizePolicy(sizePolicy)
        self.camera_frame.setStyleSheet("background:black")
        self.camera_frame.setObjectName("camera_frame")
        self.layout_main.addWidget(self.camera_frame, 1, 0, 1, 2)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, form_camera):

        _translate = QtCore.QCoreApplication.translate
        form_camera.setWindowTitle(_translate("form_camera", "Form"))
        self.btn_cancel.setText(_translate("form_camera", "Ẩn"))
        self.btn_apply.setText(_translate("form_camera", "Chấp nhận"))
        self.label_show.setText(_translate("form_camera", "Hiển thị:"))
        self.label_rtsp.setText(_translate("form_camera", "RTPS: "))
        self.label_camera_id.setText(_translate("form_camera", "CamID"))
        for k, v in self.cb_model_dict.items():
            print(k, v)
            self.combo_features.setItemText(v, _translate("form_camera", f"{k}"))
        self.camera_frame.setText(_translate("form_camera", "TextLabel"))
        self.btn_delete_cam.setText(_translate("form_camera", "Xóa cam"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ui = Widget_Camera_Item()
    ui.form.show()
    sys.exit(app.exec_())
