# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'layout_info_tableui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from operator import is_
from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd
import sqlite3


class Ui_Info_Table(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi()
        self.db = 'Database\huyquang.db'
        # self.db_to_df()
        # self.show_table()
    
    def db_to_df(self):
        self.conn = sqlite3.connect(self.db)
        self.df = pd.read_sql_query("SELECT * FROM parking", self.conn)
    
    def show_table(self):
        df = self.df.drop(['id', "img_path"], axis=1)
        self.table.setRowCount(len(df))
        self.table.setColumnCount(len(df.columns))
        self.table.setHorizontalHeaderLabels(df.columns)
        header = self.table.horizontalHeader()
        for i in range(df.columns.size):
            # header.setSectionResizeMode(i, QtWidgets.QHeaderView.ResizeToContents)       
            header.setSectionResizeMode(i, QtWidgets.QHeaderView.Stretch)
        for i in range(len(df)):
            for j in range(len(df.columns)):
                self.table.setItem(i, j, QtWidgets.QTableWidgetItem(str(df.iloc[i, j])))
    
    def setupUi(self):
        self.setObjectName("Info Table")
        self.resize(600, 300)
        
        self.query = QtWidgets.QLineEdit(self)
        self.query.setPlaceholderText("Search...")
        self.query.textChanged.connect(self.slot_query)
        self.table = QtWidgets.QTableWidget(self)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        layout = QtWidgets.QVBoxLayout(self)
        layout.setObjectName("layout")
        layout.addWidget(self.query)
        layout.addWidget(self.table)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Info Table", "Info Table"))

    def slot_query(self, s):
        self.table.setCurrentItem(None)
        if not s:
            return
        name = s.lower()
        for row in range(self.table.rowCount()):
            is_in_query = False
            for col in range(self.table.columnCount()):
                item = self.table.item(row, col)
                is_in_query = name in item.text().lower()
                if is_in_query:
                    break
            self.table.setRowHidden(row, not is_in_query)
        # matching_items = self.table.findItems(s, QtCore.Qt.MatchContains)
        # if matching_items:
        #     for item in matching_items:
        #         # item = matching_items[0]
        #         self.table.setCurrentItem(item)        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_Info_Table()
    ui.db = "D:\Lab IC\datn\Database\huyquang.db"
    ui.db_to_df()
    ui.show_table()
    ui.show()
    sys.exit(app.exec_())
